### PR TITLE
Fix style game loop

### PR DESCRIPTION
**Pull request by nashirj**
Updated all game loop files to have more clear comments and to adhere to pylint suggestions.

### CODE REVIEW

**Comment by ryPattillo** [comment]
Looks good to me

**Comment by LSaber36** [comment]
Looks good to me :)

**Comment by LSaber36** [comment]
I am wondering though, is it standard/well accepted to use that format for functions? Specifically:

this_style
vs
thisStyle

**Comment by nashirj** [comment]
@LSaber36 yes, the style guide we are following has a section on [function naming](https://google.github.io/styleguide/pyguide.html#316-naming) and they use `function_name` as opposed to `functionName`.

**Comment by JuddBE** [comment]
Looks good

**Comment by LSaber36** [comment]
Oh awesome, I was wondering if the python code was going to have a style guide similar to the arduino code having it's style guide. Thanks for letting me know about it!

**Comment by nashirj** [comment]
Of course @LSaber36 !

**Pull request merged**
