### PR TITLE
Added a working CNN example

### PR DESCRIPTION
**Pull request by owenonline**
Added the code for a working CNN example for other people in the AI team to look at, and updated the gitignore to not commit the large image training set used. Note that to replicate my results you must download and extract the CIFAR10 training set to the data folder yourself prior to running; I experienced SSL errors when trying to have the code download the dataset automatically. Save yourself the hassle, the link is here: https://www.cs.toronto.edu/~kriz/cifar.html

### CODE REVIEW

**Comment by nashirj** [comment]
Also, if you do not include `download=True` in creating the dataloader, can you at least leave a comment in the source about needing that data and that you can download it from the link you provided or by adding that flag? Thanks

**Comment by ryPattillo** [comment]
Went ahead and moved my code over to the MNIST_MLP.py and created a pull request. I saw my name tagged and I thought you meant for me to do it.

**Comment by nashirj** [comment]
Thanks for doing that @ryPattillo ! Now you can just fix the merge conflicts and rename the file and I'll merge this in @owenonline

**Comment by owenonline** [comment]
Alright I put my code in CIFAR_CNN.py; I see that @ryPattillo has already put his code in MNIST_MLP.py. Does this resolve the conflict?

**Comment by nashirj** [comment]
There are still conflicts in `pytorch_experimenting.py`. You can just delete that file and then we'll be good

**Comment by nashirj** [comment]
Alternatively you can reset the changes to that file and then I will delete in a separate PR

**Comment by owenonline** [comment]
I deleted it 👍

**Comment by nashirj** [comment]
I fixed the merge conflict. Here are the commands showing what I did so you can do it next time: https://pastebin.com/Ji71aF9u

You'll know if you have conflicts because the box at the bottom will be greyed out and won't allow pressing the button that says "Merge pull request"

**Comment by owenonline** [comment]
Alright thank you!

**Comment by nashirj** [comment]
np!

**Pull request merged**
