### PR TITLE
Game loop capture update

### LINKED ISSUE #116: Update how piece captures behave in game loop (for engine/cli)
If it's a capture:
1) Send captured piece to the proxy temp spot (need to determine which direction capturing piece is coming from and pick a corner that is out of the way).
2) Send capturing piece to destination square.
3) Send captured piece to graveyard.

Need to update serial messaging scheme to have "~<MOVE_TO_TEMP><START_SQ><LL/LR/UL/UR><MOVE_COUNT>". This issue should be addressed on both the Arduino and Pi sides.

### PR DESCRIPTION
**Pull request by nashirj**
This PR closes #116 . It also updates the board representation on the Pi side to index the board as a 25x25 grid instead of a 12x12 grid. This allows not only accessing the center of cells, but the corners and sides as well. The representation is explained in `boardinterface.Board.get_board_coords_from_square()`.

### CODE REVIEW

**Comment by LSaber36** [comment]
Looks good to me

**Comment by LSaber36** [comment]
Whoops I accidentally closed it. I reopened it.

**Review by ryPattillo — COMMENTED** [review]
Looks good!

**Comment by nashirj** [comment]
Thanks for the review! There a couple small changes I need to make, but I'll merge it after those.

**Pull request closed without merging**
